package dev.systemslibrarian.truepad.app

/*
 * THE CLAIMS TEXT, carried over from the released Browser Edition.
 *
 * Every constant here is the released src/browser/ui/source-claims.ts string at
 * tag v2.0.0, reproduced verbatim except where a sentence names a browser API
 * that does not exist on Android. Those substitutions are marked ANDROID and are
 * the only edits; the shape of each claim — what it asserts, what it refuses to
 * assert, and how conditional it stays — is unchanged.
 *
 * This file is not decoration. TruePad's product claims are audited, and the
 * difference between "uniform if at least one source was uniform" and "your pad
 * is truly random" is the difference between an honest product and a lie. An
 * Android edition that reworded these into something friendlier would be making
 * claims the release deliberately does not make.
 *
 * FORBIDDEN on the randomness path, in any edition: "verified", "certified",
 * "passed", "confirmed", "proven", "true randomness", "truly random" (except
 * inside CANNOT_VERIFY, which denies it), "perfect secrecy achieved",
 * "information-theoretic security confirmed"; and — since the 3.0 port — the
 * deployment overclaims "maximum assurance", "gold standard", "perfect secrecy",
 * "verified random", "certified entropy" as positive assertions.
 * AppSourceAuditTest.noClaimAssertsWhatTheProductRefusesToClaim enforces this.
 */
object Claims {

    /* ---- device-generated: the normal path -------------------------------- */

    /** Level 1. What a person who has never heard of a CSPRNG needs, and no more. */
    const val DEVICE_SHORT = "TruePad uses your device's cryptographic random generator."

    /**
     * Level 3. Exact, and exact about what it does NOT claim.
     * ANDROID: names SecureRandom, the platform generator actually used here,
     * where the browser text names crypto.getRandomValues. Nothing else differs.
     */
    const val DEVICE_DETAIL =
        "Generated by your device's cryptographic random generator (java.security.SecureRandom) — a " +
            "cryptographically secure platform generator, or CSPRNG. Its security rests on computational and " +
            "platform assumptions. TruePad does not call this physically proven randomness, and does not promote " +
            "it to an unconditional information-theoretic source claim."

    const val DEVICE_SOURCE_LABEL = "Device-generated"

    /**
     * The declaredOrigin recorded in head.json for the platform source. ANDROID:
     * same sentence as the release with the generator renamed. This string
     * travels in the courier bundle, so it is what a peer on any edition reads
     * about where this pad came from.
     */
    const val DEVICE_DECLARED_ORIGIN =
        "Generated by your device's cryptographic random generator (java.security.SecureRandom) — a computational " +
            "CSPRNG source, not verified physical randomness."

    /** The source NAME recorded in head.json. Matches the released browser's. */
    const val DEVICE_SOURCE_NAME = "device-random"

    /* ---- external material: the expert ceremony --------------------------- */

    const val EXTERNAL_SHORT = "Supply random material whose origin you control."

    const val CEREMONY_TITLE = "True OTP ceremony"

    const val CEREMONY_COMBINER = "TruePad combines every selected source byte-for-byte using XOR."

    const val CEREMONY_CONDITIONAL =
        "If at least one source is actually uniform and independent of the others, the combined material is uniform."

    /** Load-bearing: this is what stops the ceremony from reading as an act of randomness generation. */
    const val CEREMONY_CANNOT_VERIFY = "TruePad cannot determine whether a file is truly random."

    const val CEREMONY_SECRECY =
        "At least one combined source must also be secret from the adversary. Material an adversary can obtain " +
            "may still be XORed in — however uniform it is, it cannot be the source that carries the guarantee. " +
            "Never combine material an adversary supplied, chose, or could have influenced: a source chosen " +
            "against yours can cancel it."

    const val CEREMONY_MESSAGE_INDEPENDENCE =
        "Never derive source material from the messages you plan to send. A file that came from the same events " +
            "as your message is not independent of it."

    /**
     * ANDROID: the platform's own identity limitation, stated rather than
     * invented around. The browser says its file API exposes no filesystem
     * identity. Android's picker does return a document URI, so TruePad refuses
     * the SAME URI twice in one ceremony — but that is a string comparison and
     * nothing more: two different URIs can still resolve to one underlying file,
     * and TruePad will not inspect source bytes to guess.
     */
    const val CEREMONY_ALIASING =
        "TruePad refuses the same picked file twice in one ceremony, but that is a comparison of what the picker " +
            "returned and nothing more: two different picks can still resolve to the same underlying file, and " +
            "TruePad will not inspect your source bytes to guess. Choosing one file twice by another route is " +
            "yours to avoid."

    fun ceremonyLengthRule(required: Long): String =
        "Every source must independently supply the full ${groupDigits(required)} bytes. Sources are never " +
            "concatenated and never split between them — each one covers the whole pad — and anything beyond " +
            "that length is unused."

    /* ---- the operator declaration ----------------------------------------- */

    /** An OPERATOR DECLARATION. Not a test, not a result, not a verification. */
    const val OPERATOR_DECLARATION =
        "I understand that TruePad cannot verify physical randomness. For an information-theoretic one-time-pad " +
            "secrecy claim about this pad's material, at least one selected source must actually be uniformly " +
            "random, secret from the adversary, and never previously used. That source must also be independent " +
            "of all the other selected sources taken together, and of the messages this pad will protect. It must " +
            "never be used to make another pad."

    /* ---- the created pad's source claim ------------------------------------ */

    const val EXTERNAL_SOURCE_LABEL = "External material — operator declared"

    const val EXTERNAL_NOT_VERIFIED = "TruePad did not verify that assumption."

    const val EXTERNAL_CONDITIONAL =
        "If that source assumption is true, the pad material satisfies the information-theoretic randomness " +
            "requirement of a one-time pad."

    const val EXTERNAL_BEYOND_UNIFORMITY =
        "The verdict above is about uniformity only. An information-theoretic secrecy claim would also require " +
            "that the source material you supplied was, and stays, secret from the adversary; that it was " +
            "independent of the messages this pad will protect, in either direction; that no other pad is ever " +
            "derived from it; and that this pad material is used exactly once. TruePad's counters enforce that " +
            "last condition within TruePad — a copy of the pad file made outside it is beyond them. TruePad " +
            "established none of the rest; that is what you declared."

    /* ---- pad delivery ------------------------------------------------------ */

    const val DELIVERY_ESSENTIAL =
        "Anyone who holds it can read and forge this pad's messages. Hand it over in person, or send it on a " +
            "channel only the two of you control — never email, upload, or sync it."

    const val DELIVERY_CEREMONY =
        "For an end-to-end information-theoretic secrecy claim, the pad file must also be delivered through a " +
            "secret method whose confidentiality does not itself depend on computational encryption assumptions. " +
            "Physical handoff on removable media is the clearest ceremony."

    const val DELIVERY_NOT_ITS =
        "Email, Dropbox, Google Drive, OneDrive, ordinary cloud storage and encrypted messengers do not preserve " +
            "that claim. They may be computationally secure ways to move a file — that is a different guarantee, " +
            "not a weaker form of this one."

    /* ---- Android-specific honesty ------------------------------------------ */

    /**
     * The clipboard is a cross-application surface. Saying so is the whole
     * mitigation; TruePad cannot police what other apps read.
     */
    const val CLIPBOARD_WARNING =
        "Anything you copy can be read by other apps on this device. TruePad marks it as sensitive where Android " +
            "supports that, which asks the system not to preview it — it does not stop another app from reading " +
            "the clipboard."

    /**
     * FLAG_SECURE is set on the window, and this says exactly what that buys.
     */
    const val SCREEN_CAPTURE_NOTE =
        "TruePad asks Android to keep its screens out of screenshots and the recent-apps preview. That is a " +
            "request to the system, not a defence against a device someone else controls."

    /* ---- deployment assessment (§ shannon) --------------------------------- */

    /**
     * What the deployment classification means, and — load-bearing — the ceiling
     * an Android device imposes on it. This DENIES the strong claim rather than
     * asserting it: an Android pad is never the maximum-assurance profile, because
     * the device has no hardware-monotonic authority to attest that a pad was
     * never rolled back. The strongest result here is "insufficient evidence,"
     * never a positive maximum-assurance verdict, and TruePad says so plainly.
     */
    const val DEPLOYMENT_CONTEXT =
        "This is TruePad's own reading of whether this pad could still support an information-theoretic secrecy " +
            "claim, derived from what it can record — never a stored verdict. It is not a score, and a strong " +
            "result would still not prove the physical premises below. An Android pad is never TruePad's maximum-" +
            "assurance profile: this device has no hardware-monotonic authority to attest a pad was never restored " +
            "from a backup, so the strongest result you will see here is \"insufficient evidence,\" never a positive " +
            "maximum-assurance verdict."

    /** The heading over the premises TruePad never establishes, even at its best. */
    const val DEPLOYMENT_UNPROVEN_HEADING =
        "Even at its strongest, TruePad does not establish these — they are yours:"

    /** Backup posture, in one sentence a person can act on. */
    /* ---- the About destination -------------------------------------------
     *
     * PORTED VERBATIM FROM THE iOS EDITION, which had an About screen while this
     * one did not. The claims boundary in particular is a fixed cross-edition
     * statement: the two apps must say the same three sentences in the same
     * words, and `AboutParityTest` fails if they drift.
     *
     * Two constants are NOT here because this edition already has them, with the
     * same wording, in the storage module: DESTROY_LIMITATION and GEN_VERDICT.
     * Copying them would have created a second place for §17 and §7 to be wrong.
     */

    /** PQC protects DELIVERY. Never the message. */
    const val CLAIM_DELIVERY = "Post-quantum cryptography protects pad DELIVERY."
    const val CLAIM_ENCRYPTION = "The one-time pad encrypts messages."
    const val CLAIM_AUTHENTICATION = "Wegman–Carter authenticates messages."

    const val NO_SERVER = "No server, no account, no transport of its own"

    /** "No logging" means nothing TRUEPAD writes reaches the system log or a third
     *  party. Each pad still keeps its own on-disk journal, and conflating the two
     *  would read as "nothing is written down". See [LOG_SCOPE], which says the
     *  same thing to the operator instead of only to a reader of this file. */
    const val NO_TELEMETRY =
        "No analytics, no crash reporting, nothing written to the system log"

    /**
     * THE SCOPE OF THE SENTENCE ABOVE, said on screen rather than left implied.
     *
     * `AppSourceAuditTest.theAppLogsNothing` bans logging symbols in TruePad's own
     * source, which is the whole of what that guard can see. It is not the whole
     * of what runs in TruePad's process: scanning a receive code uses the platform
     * camera and barcode libraries, and both write ordinary diagnostic lines to
     * the system log as a matter of course. An operator — or a reviewer checking
     * these claims — who runs `adb logcat --pid $(adb shell pidof
     * dev.systemslibrarian.truepad)` and opens the scanner sees them immediately,
     * and a flat "nothing written to the system log" is contradicted by the first
     * line they read.
     *
     * The two clauses beside it are genuinely earned — INTERNET is removed from
     * the manifest and the datatransport entry points are deleted — which makes
     * the third one's overreach easier to miss and more costly when it is found.
     *
     * What is true, and what the claim exists to promise, is that none of what is
     * written is about the operator.
     */
    const val LOG_SCOPE =
        "TruePad itself writes nothing to the system log. The camera and barcode libraries it " +
            "uses to scan a code write their own ordinary diagnostic lines there; none of it " +
            "carries your pads, your messages, or anything about them."

    /** ACCURATE ABOUT THE DEFAULT. Pads normally come from this device, and that
     *  is a permanent disqualifier for the strongest classification. */
    const val PADS_ARE_DEVICE_GENERATED =
        "Pads are normally generated by this device. That is a strong practical source, and it " +
            "reads NOT ELIGIBLE for the strongest deployment classification — permanently. " +
            "Supplying your own physical random material is the path to that classification."

    /** What a QR code is, and is not. */
    const val QR_CARRIES_ONLY_PUBLIC_DATA =
        "This code carries only public data — a one-time request key, or an already-encrypted " +
            "message. It never contains pad material, and photographing it does not reveal " +
            "anything the pad protects."

    /** A CARRIER, NOT A TRANSPORT. The apps named here are this platform's, which
     *  is the one place this text legitimately differs from the iOS wording. */
    const val SHARE_IS_A_CARRIER =
        "TruePad hands this file to whatever you choose — a messaging app, Drive, Nearby Share. " +
            "It has no server, no account, and no transport of its own, and it cannot tell you " +
            "what happens to the file afterwards."

    const val BACKUP_NOTE =
        "TruePad is excluded from Android backup and device-to-device transfer. A pad is one-time material, and a " +
            "restored copy of one is exactly the failure this app exists to prevent — so pads do not travel to a " +
            "new phone, and uninstalling removes them for good."

    private fun groupDigits(n: Long): String {
        val s = n.toString()
        val sb = StringBuilder()
        for ((i, c) in s.withIndex()) {
            if (i > 0 && (s.length - i) % 3 == 0) sb.append(',')
            sb.append(c)
        }
        return sb.toString()
    }
}
