/* ============================================================================
 * The Android-generated SPT corpus — the Browser/CLI side.
 * ----------------------------------------------------------------------------
 * android/vectors/spt-android-generated.json is generated by the Android Edition
 * (android/truepad-spt, CryptoV1.kt sealPayloadV1). It is the third leg of the
 * interop matrix, and it was the missing one:
 *
 *   android/vectors/spt-interop.json         TypeScript-sealed.  Opened by
 *                                            TypeScript, Swift and Kotlin.
 *   ios/vectors/spt-swift-generated.json     Swift-sealed.       Opened by
 *                                            TypeScript, Swift and Kotlin.
 *   android/vectors/spt-android-generated.json
 *                                            Kotlin-sealed.      Opened by Swift
 *                                            and Kotlin — and, until this file,
 *                                            NOT by TypeScript.
 *
 * The corpus's own header says it exists "so the other editions can open bytes
 * ANDROID produced". TypeScript is one of the other editions, and the matrix was
 * asymmetric without this.
 *
 * WHY THE ASYMMETRY MATTERED, rather than being tidiness. Kotlin reproducing the
 * TypeScript corpus proves Kotlin's SEAL agrees with TypeScript's seal on fixed
 * entropy. It does NOT prove TypeScript's OPEN accepts what Kotlin's production
 * path actually emits, because every derandomized corpus bypasses production
 * encapsulation — a fault confined to Kotlin's real-entropy path would be
 * invisible to all of the derandomized checks. The reproducible=false cases here
 * are exactly that path, and this is the only place TypeScript meets them.
 * ========================================================================= */

import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { bytesToHex, hexToBytes } from "../src/core/hex.ts";
import { openPayloadV1, sealPayloadV1 } from "../src/spt/crypto-v1.ts";

interface Case {
  label: string;
  reproducible: boolean;
  eseedHex?: string;
  requestBodyHex: string;
  decapSeedHex: string;
  payloadHex: string;
  packageHex: string;
  confirmValueHex: string;
  confirmationIndices: number[];
}

const corpus = JSON.parse(
  readFileSync(resolve(import.meta.dirname, "../android/vectors/spt-android-generated.json"), "utf8")
) as { note: string; source: string; cases: Case[] };

const hx = (s: string) => hexToBytes(s)!;

describe("Android-generated SPT corpus (Browser/CLI side)", () => {
  it("is non-trivial and still the Android seal output", () => {
    expect(corpus.cases.length).toBeGreaterThanOrEqual(6);
    expect(corpus.source).toContain("android/truepad-spt");
    // BOTH KINDS MUST BE PRESENT. A corpus that quietly lost its
    // reproducible=false cases would still pass every assertion below while no
    // longer testing the production-entropy path, which is the whole reason this
    // file exists.
    expect(corpus.cases.some((c) => c.reproducible)).toBe(true);
    expect(corpus.cases.some((c) => !c.reproducible)).toBe(true);
  });

  for (const c of corpus.cases) {
    it(`${c.label}: this implementation opens the Android-sealed package`, async () => {
      const opened = await openPayloadV1(hx(c.packageHex), hx(c.requestBodyHex), hx(c.decapSeedHex));
      expect(opened.ok).toBe(true);
      if (!opened.ok) return;
      expect(bytesToHex(opened.result.payload)).toBe(c.payloadHex);
      // The ceremony values must match too: two people comparing words across a
      // Browser/Android pair have to read the same eight words.
      expect(bytesToHex(opened.result.confirmValue)).toBe(c.confirmValueHex);
      expect(opened.result.confirmationIndices).toEqual(c.confirmationIndices);
    });

    if (c.reproducible) {
      it(`${c.label}: TypeScript reseals the Android inputs to identical bytes`, async () => {
        expect(c.eseedHex).toBeDefined();
        const sealed = await sealPayloadV1(hx(c.requestBodyHex), hx(c.payloadHex), {
          eseedForVectorsOnly: hx(c.eseedHex!)
        });
        expect(bytesToHex(sealed.packageBytes)).toBe(c.packageHex);
        expect(bytesToHex(sealed.confirmValue)).toBe(c.confirmValueHex);
        expect(sealed.confirmationIndices).toEqual(c.confirmationIndices);
      });
    }
  }
});
