/* ============================================================================
 * The iOS-generated SPT corpus — the Browser/CLI side.
 * ----------------------------------------------------------------------------
 * ios/vectors/spt-swift-generated.json is generated by the iOS Edition
 * (ios/TruePadKit, `swift run spt-vector-tool`). It points the opposite way from
 * android/vectors/spt-interop.json: those are TypeScript packages that Kotlin and
 * Swift must open, these are SWIFT packages that TypeScript must open.
 *
 * Two kinds of case, and the distinction matters:
 *
 *   reproducible: true   sealed with fixed entropy, from the same inputs as the
 *                        TypeScript corpus. This implementation must reproduce
 *                        them byte-for-byte AND open them.
 *   reproducible: false  sealed with REAL entropy on the iOS production path.
 *                        Nobody can reproduce those bytes — not even a rerun of
 *                        the generator — so they are opened, not compared. They
 *                        exist because the derandomized fixtures never exercise
 *                        production encapsulation at all, and a fault confined to
 *                        that path would otherwise be invisible to every corpus.
 * ========================================================================= */

import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { bytesToHex, hexToBytes } from "../src/core/hex.ts";
import { openPayloadV1, sealPayloadV1 } from "../src/spt/crypto-v1.ts";

interface Case {
  label: string;
  reproducible: boolean;
  eseedHex?: string;
  requestBodyHex: string;
  decapSeedHex: string;
  payloadHex: string;
  packageHex: string;
  confirmValueHex: string;
  confirmationIndices: number[];
}

const corpus = JSON.parse(
  readFileSync(resolve(import.meta.dirname, "../ios/vectors/spt-swift-generated.json"), "utf8")
) as { note: string; source: string; cases: Case[] };

const hx = (s: string) => hexToBytes(s)!;

describe("iOS-generated SPT corpus (Browser/CLI side)", () => {
  it("is non-trivial and still the iOS seal output", () => {
    expect(corpus.cases.length).toBeGreaterThanOrEqual(6);
    expect(corpus.source).toContain("ios/TruePadKit");
    expect(corpus.cases.some((c) => c.reproducible)).toBe(true);
    expect(corpus.cases.some((c) => !c.reproducible)).toBe(true);
  });

  for (const c of corpus.cases) {
    it(`${c.label}: this implementation opens the iOS-sealed package`, async () => {
      const opened = await openPayloadV1(hx(c.packageHex), hx(c.requestBodyHex), hx(c.decapSeedHex));
      expect(opened.ok).toBe(true);
      if (!opened.ok) return;
      expect(bytesToHex(opened.result.payload)).toBe(c.payloadHex);
      // The ceremony values must match too: two people comparing words across a
      // Browser/iOS pair have to read the same eight words.
      expect(bytesToHex(opened.result.confirmValue)).toBe(c.confirmValueHex);
      expect(opened.result.confirmationIndices).toEqual(c.confirmationIndices);
    });

    if (c.reproducible) {
      it(`${c.label}: TypeScript reseals the iOS inputs to identical bytes`, async () => {
        expect(c.eseedHex).toBeDefined();
        const sealed = await sealPayloadV1(hx(c.requestBodyHex), hx(c.payloadHex), {
          eseedForVectorsOnly: hx(c.eseedHex!)
        });
        expect(bytesToHex(sealed.packageBytes)).toBe(c.packageHex);
        expect(bytesToHex(sealed.confirmValue)).toBe(c.confirmValueHex);
        expect(sealed.confirmationIndices).toEqual(c.confirmationIndices);
      });
    }
  }
});
