package dev.systemslibrarian.truepad.spt

import dev.systemslibrarian.truepad.core.JsonArray
import dev.systemslibrarian.truepad.core.JsonNumber
import dev.systemslibrarian.truepad.core.JsonObject
import dev.systemslibrarian.truepad.core.JsonString
import dev.systemslibrarian.truepad.core.bytesToHex
import dev.systemslibrarian.truepad.core.hexToBytes
import dev.systemslibrarian.truepad.core.parseJson
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * GATES 3-5 — cross-language SPT interoperability, both directions.
 *
 * android/vectors/spt-interop.json is generated by the RELEASED TypeScript
 * (scripts/gen-spt-interop.ts): full derandomized seals plus each package's
 * request body and decapsulation seed. For every case this proves:
 *
 *   - BROWSER -> ANDROID: Kotlin OPENS the TS-sealed `packageHex` and recovers
 *     exactly `payloadHex` (and the same confirmation value/indices).
 *   - ANDROID -> BROWSER: Kotlin re-seals the same inputs and produces the
 *     byte-identical `packageHex` — so the TS opener (which opens its own byte-
 *     identical output, self-checked at generation) opens an Android package too.
 *
 * Honest randomized seals interoperate by construction: these deterministic
 * cases prove the primitives and wire agree exactly.
 */
class SptInteropTest {

    private fun hx(s: String) = hexToBytes(s) ?: error("bad hex: $s")

    private data class Case(
        val label: String,
        val eseed: ByteArray,
        val requestBody: ByteArray,
        val decapSeed: ByteArray,
        val payload: ByteArray,
        val packageBytes: ByteArray,
        val confirmValue: ByteArray,
        val indices: IntArray,
    )

    private val cases: List<Case> = run {
        val root = parseJson(File("../vectors/spt-interop.json").readText()) as JsonObject
        (root.members.getValue("cases") as JsonArray).items.map { it as JsonObject }.map { o ->
            fun s(k: String) = (o.members.getValue(k) as JsonString).value
            val idx = (o.members.getValue("confirmationIndices") as JsonArray).items
                .map { (it as JsonNumber).raw.toInt() }.toIntArray()
            Case(s("label"), hx(s("eseedHex")), hx(s("requestBodyHex")), hx(s("decapSeedHex")),
                hx(s("payloadHex")), hx(s("packageHex")), hx(s("confirmValueHex")), idx)
        }
    }

    @Test
    fun theCorpusIsPresentAndNonTrivial() {
        assertTrue("expected interop cases", cases.size >= 3)
    }

    @Test
    fun androidOpensEveryBrowserSealedPackage() {
        for (c in cases) {
            val opened = openPayloadV1(c.packageBytes, c.requestBody, c.decapSeed)
            assertTrue("${c.label}: Android must open the Browser package", opened is OpenOutcome.Ok)
            val r = (opened as OpenOutcome.Ok).result
            assertArrayEquals("${c.label}: recovered payload", c.payload, r.payload)
            assertEquals("${c.label}: confirmValue", bytesToHex(c.confirmValue), bytesToHex(r.confirmValue))
            assertArrayEquals("${c.label}: confirmationIndices", c.indices, r.confirmationIndices)
        }
    }

    @Test
    fun androidReSealsToTheByteIdenticalBrowserPackage() {
        // If Android's seal output equals the Browser's byte-for-byte, then the
        // Browser opener (which opens that byte sequence) opens Android packages.
        for (c in cases) {
            val sealed = sealPayloadV1(c.requestBody, c.payload, eseedForVectorsOnly = c.eseed)
            assertEquals("${c.label}: Android seal == Browser seal", bytesToHex(c.packageBytes), bytesToHex(sealed.packageBytes))
            assertEquals("${c.label}: confirmValue", bytesToHex(c.confirmValue), bytesToHex(sealed.confirmValue))
        }
    }
}
