/* ============================================================================
 * Shannon deployment assessment — a DERIVED classification, never a verdict
 * ----------------------------------------------------------------------------
 * TruePad's message cipher is a literal one-time-pad XOR. That is a fact about
 * the COMBINER. It is a different thing from whether a PARTICULAR DEPLOYMENT
 * still satisfies the premises under which Shannon's information-theoretic
 * confidentiality theorem may be invoked — sufficient fresh pad, a genuinely
 * uniform source, secrecy/independence, one-time use, private delivery, and
 * state discipline.
 *
 * Software can enforce or support parts of the pad-length, one-time-use and
 * state-discipline premises. It CANNOT prove physical randomness, source
 * independence, that only the intended parties hold the pad, private courier
 * behaviour, the absence of hidden copies, or physical erasure.
 *
 * So this module NEVER decides "secure". It maps a small set of FACTS that
 * TruePad has actually recorded to one of three eligibility outcomes, and it
 * refuses to promote the unknown. There is no persisted verdict: the caller
 * derives the facts fresh from durable provenance every time, and this pure
 * function classifies them. Nothing here is written to any store — there is no
 * `trueRandom`, no `informationTheoretic`, no `itCapable` flag, and none may be
 * added (Store Format v2 stays frozen; see docs/SHANNON-DEPLOYMENT.md).
 * ========================================================================= */

/** How the pad MATERIAL was sourced — premise B/C (uniformity, secrecy). */
export type SourceClass =
  /** An operator-supplied external source, declared at gen/ceremony. TruePad
   *  recorded the declaration; it verified none of the physics. */
  | "external-declared"
  /** A software CSPRNG (e.g. crypto.getRandomValues). A real, useful source —
   *  and a COMPUTATIONAL assumption, not the physical-uniform-source premise. */
  | "software-csprng"
  /** Provenance TruePad cannot establish (an arbitrary import, a legacy store). */
  | "unknown";

/** How the pad was DELIVERED to its intended holder — premise E (only the
 *  intended parties obtained it). */
export type DeliveryClass =
  /** Generated on this device; TruePad has not distributed it. */
  | "local-generation"
  /** Couriered privately on physical media. TruePad cannot observe a courier,
   *  so this is always an OPERATOR premise, never a verification. */
  | "private-handoff-operator-asserted"
  /** Delivered as a `.tps2` sealed package under computational cryptography
   *  (X-Wing / HKDF / AES-GCM). Positively COMPUTATIONAL end to end. */
  | "sealed-online"
  /** Imported from a file whose delivery TruePad cannot establish. */
  | "raw-import-unknown"
  /** Delivery not establishable. */
  | "unknown";

/** The three outcomes. Never SECURE/INSECURE, never TRUE/FALSE OTP. */
export type ShannonAssessment = "conditionally-eligible" | "not-eligible" | "insufficient-evidence";

/** The derived facts a caller assembles from durable provenance. */
export interface DeploymentFacts {
  sourceClass: SourceClass;
  deliveryClass: DeliveryClass;
}

export interface DeploymentAssessment {
  assessment: ShannonAssessment;
  /** A short, factual reason when a disqualifying or unknown fact drove it.
   *  Present for not-eligible and insufficient-evidence; absent otherwise. */
  knownReason?: string;
}

/**
 * Classify a deployment from recorded facts. Pure and total. Ordering is
 * deliberate and load-bearing:
 *
 *   1. A KNOWN disqualifying path (software CSPRNG source, or sealed
 *      computational delivery) is NOT ELIGIBLE — and can never be promoted.
 *   2. An UNKNOWN source or delivery is INSUFFICIENT EVIDENCE — absence of
 *      evidence is never treated as an ideal ceremony.
 *   3. Only an operator-declared external source with no recorded disqualifying
 *      delivery is CONDITIONALLY ELIGIBLE — and even then TruePad has proved
 *      none of the physical premises.
 */
export function assessShannonDeployment(facts: DeploymentFacts): DeploymentAssessment {
  if (facts.sourceClass === "software-csprng") {
    return { assessment: "not-eligible", knownReason: "source material was generated by a software CSPRNG" };
  }
  if (facts.deliveryClass === "sealed-online") {
    return { assessment: "not-eligible", knownReason: "pad delivery depended on computational cryptography" };
  }
  if (
    facts.sourceClass === "unknown" ||
    facts.deliveryClass === "raw-import-unknown" ||
    facts.deliveryClass === "unknown"
  ) {
    return { assessment: "insufficient-evidence", knownReason: "source or delivery provenance is unknown" };
  }
  return { assessment: "conditionally-eligible" };
}

/* ---- display vocabulary --------------------------------------------------- */

export const ASSESSMENT_LABEL: Record<ShannonAssessment, string> = {
  "conditionally-eligible": "CONDITIONALLY ELIGIBLE",
  "not-eligible": "NOT ELIGIBLE",
  "insufficient-evidence": "INSUFFICIENT EVIDENCE"
};

export const SOURCE_LABEL: Record<SourceClass, string> = {
  "external-declared": "external, operator-declared",
  "software-csprng": "software random generator",
  unknown: "unknown"
};

export const DELIVERY_LABEL: Record<DeliveryClass, string> = {
  "local-generation": "generated locally",
  "private-handoff-operator-asserted": "private handoff (operator premise)",
  "sealed-online": "sealed online (computational)",
  "raw-import-unknown": "imported (unknown)",
  unknown: "unknown"
};

/** The qualifier that MUST accompany a CONDITIONALLY ELIGIBLE result wherever it
 *  is shown, so the label can never be screenshot alone as "secure". */
export const CONDITIONAL_CAVEAT =
  "TruePad has recorded no known disqualifying path. It has not proved physical randomness, source independence, " +
  "the absence of copies, private courier behaviour, the absence of a restore, or physical erasure.";
