/* ============================================================================
 * TruePad Browser Edition — the randomness SOURCE claim, worded once
 * ----------------------------------------------------------------------------
 * The governing rule of the whole project applies hardest here:
 *
 *   The XOR is already a true one-time pad. The machinery only keeps the
 *   theorem's hypotheses true OUTSIDE the equation. Never promote an
 *   engineering action into a stronger cryptographic claim than it deserves.
 *
 * So the COMBINER and the SOURCE are graded separately, and this module keeps
 * the two apart in the only place a user reads them — the words.
 *
 *   COMBINER (both paths, unconditional): every declared source supplies the
 *   complete L = 2·(E + 32·N) bytes; they are XORed byte-for-byte; the result
 *   is partitioned into the four secret slices. No KDF, no extractor, no hash
 *   conditioner, no whitening, no statistical gate, no content-dependent
 *   rejection. This is exact, and it is the same on both paths.
 *
 *   SOURCE (graded, and NOT the same on the two paths):
 *     · Device-generated — crypto.getRandomValues(). A cryptographically
 *       secure platform generator. COMPUTATIONAL: its security rests on
 *       platform and computational assumptions. Never called physically
 *       proven, verified, or information-theoretic.
 *     · External ceremony — operator-supplied material. ELIGIBLE for the
 *       information-theoretic premise, and only eligible: the premise is true
 *       if and only if the operator's physical assumptions are actually true,
 *       which no software can determine. The claim therefore stays
 *       conditional, in every sentence, forever.
 *
 * The operator declaration below is an OPERATOR DECLARATION and never a
 * verification result. Nothing here may ever read "verified", "certified",
 * "passed", "confirmed", or "proven".
 *
 * The verdict itself is NOT restated here on purpose: it is the engine's
 * string, shown back verbatim from the gen reply, so the UI can never drift
 * from what the combiner actually claims.
 * ========================================================================= */

/* ---- device-generated: the normal path ---------------------------------- */

// Level 1. What a person who has never heard of a CSPRNG needs, and no more.
export const DEVICE_SHORT = "TruePad uses your device's cryptographic random generator.";

// Level 3. Exact, and exact about what it does NOT claim.
export const DEVICE_DETAIL =
  "Generated by your device's cryptographic random generator (crypto.getRandomValues) — a cryptographically " +
  "secure platform generator, or CSPRNG. Its security rests on computational and platform assumptions. TruePad " +
  "does not call this physically proven randomness, and does not promote it to an unconditional " +
  "information-theoretic source claim.";

export const DEVICE_SOURCE_LABEL = "Device-generated";

/* ---- external material: the expert ceremony ----------------------------- */

export const EXTERNAL_SHORT = "Supply random material whose origin you control.";

export const CEREMONY_TITLE = "True OTP ceremony";

// The combiner, stated plainly. Both sentences are about the XOR, which is
// exact — neither one says anything about where the bytes came from.
export const CEREMONY_COMBINER = "TruePad combines every selected source byte-for-byte using XOR.";
export const CEREMONY_CONDITIONAL =
  "If at least one source is actually uniform and independent of the others, the combined material is uniform.";

// Load-bearing. Selecting this path is not an act of randomness generation,
// and this sentence is what stops the ceremony from reading as one.
export const CEREMONY_CANNOT_VERIFY = "TruePad cannot determine whether a file is truly random.";

// The source that carries the guarantee must also be SECRET from the
// adversary — a uniform, independent, but published source proves nothing.
export const CEREMONY_SECRECY =
  "The source that carries the guarantee must also be secret. Material an adversary can obtain is not a source, " +
  "however uniform it is.";

// The browser's own identity limitation, stated rather than invented around.
export const CEREMONY_ALIASING =
  "TruePad cannot tell whether two chosen files hold the same material: the browser's file API exposes no " +
  "filesystem identity to check, and TruePad will not inspect your source bytes to guess. Choosing one file " +
  "twice is yours to avoid.";

export function ceremonyLengthRule(required: number): string {
  return (
    `Every source must independently supply the full ${required.toLocaleString("en-US")} bytes. Sources are never ` +
    `concatenated and never split between them — each one covers the whole pad — and anything beyond that length ` +
    `is unused.`
  );
}

/* ---- the operator declaration ------------------------------------------- */

// An OPERATOR DECLARATION. Not a test, not a result, not a verification.
export const OPERATOR_DECLARATION =
  "I understand that TruePad cannot verify physical randomness. For an information-theoretic one-time-pad claim, " +
  "at least one selected source must actually be uniformly random, secret, independent of the other combined " +
  "sources, and never previously used.";

/* ---- the created pad's source claim ------------------------------------- */

export const EXTERNAL_SOURCE_LABEL = "External material — operator declared";

export const EXTERNAL_NOT_VERIFIED = "TruePad did not verify that assumption.";

// Conditional, and it stays conditional. Never "perfect secrecy achieved",
// never "true OTP verified", never "information-theoretic security confirmed".
export const EXTERNAL_CONDITIONAL =
  "If that source assumption is true, the pad material satisfies the information-theoretic randomness requirement " +
  "of a one-time pad.";

/* ---- pad delivery ------------------------------------------------------- */

// True on both paths, and the shortest true thing there is to say.
export const DELIVERY_ESSENTIAL =
  "Anyone who holds it can read and forge this pad's messages. Hand it over in person, or send it on a channel " +
  "only the two of you control — never email, upload, or sync it.";

// The expert half: source secrecy is only half an OTP deployment, and a
// computationally secure transfer is a DIFFERENT claim, not a weaker version
// of the same one.
export const DELIVERY_CEREMONY =
  "For an end-to-end information-theoretic secrecy claim, the pad file must also be delivered through a secret " +
  "method whose confidentiality does not itself depend on computational encryption assumptions. Physical handoff " +
  "on removable media is the clearest ceremony.";

export const DELIVERY_NOT_ITS =
  "Email, Dropbox, Google Drive, OneDrive, ordinary cloud storage and encrypted messengers do not preserve that " +
  "claim. They may be computationally secure ways to move a file — that is a different guarantee, not a weaker " +
  "form of this one.";
